apiVersion: v1
kind: Deployment
metadata: 
   app : my-app
spec:
   replicas: 2
   selector:
     matchLabels:
       app: my-app
    template:
      metadata:
        labels:
          app: my-app
      spec:
        containers:
        -  name: my-app
            image: deshnishant/shopapp
            ports:
            - containerPort: 8080
            livenessProbe:
               httpGet:
                  path: /healthz
                  port: 9090
               initialDelaySeconds: 3
               periodSeconds: 3
             resources:
               limits:
                  memory: "500Mi"
                  cpu: "500m"
                requests:
                  memory: "100Mi"
                  cpu: "100m"
               
            
              
